// Generated by tools/variants/generate.mjs; edit devices.json / peripherals.json instead.
#ifndef ARDUINO_VARIANT_STC32G144K246_H
#define ARDUINO_VARIANT_STC32G144K246_H

#define STC_VARIANT_MODEL "STC32G144K246"
#define STC_VARIANT_FAMILY "STC32G"
#define STC_FLASH_BYTES 251904UL
#define STC_MAXIMUM_CODE_BYTES 251904UL
#define STC_IDATA_BYTES 0U
#define STC_XDATA_BYTES 131072UL
#define STC_EDATA_BYTES 16384UL
#define STC_NUM_LOGICAL_DIGITAL_PINS 92U
#define STC_NUM_BONDED_DIGITAL_PINS 91U
#define STC_VARIANT_PIN_ALIAS_GROUP_COUNT 1U
#define STC_PINOUT_IS_PACKAGE_DEPENDENT 1
#define STC_VARIANT_HAS_SEPARATE_PULLUP 1
#define STC_VARIANT_HAS_UART1 1
#define STC_VARIANT_UART_COUNT 8U
#define STC_VARIANT_I2C_COUNT 2U
#define STC_VARIANT_SPI_COUNT 3U
#define STC_VARIANT_SERIAL_BUFFERED_RX 1
#define PIN_VALID_MASK_P0 0xFFU
#define PIN_VALID_MASK_P1 0xFBU
#define PIN_VALID_MASK_P2 0xFFU
#define PIN_VALID_MASK_P3 0xFFU
#define PIN_VALID_MASK_P4 0xFFU
#define PIN_VALID_MASK_P5 0x1FU
#define PIN_VALID_MASK_P6 0xFFU
#define PIN_VALID_MASK_P7 0xFFU
#define PIN_VALID_MASK_P8 0xFFU
#define PIN_VALID_MASK_P9 0xFFU
#define PIN_VALID_MASK_PA 0xFFU
#define PIN_VALID_MASK_PB 0xFFU
#define STC_VARIANT_PINS_SHARE_PHYSICAL_PAD(left, right) \
  (((((left) == (P1_3)) && ((right) == (P1_7))) || (((left) == (P1_7)) && ((right) == (P1_3)))))
#define STC_VARIANT_PHYSICAL_ALIAS(pin) \
  (((pin) == (P1_3)) ? (P1_7) : \
   ((pin) == (P1_7)) ? (P1_3) : \
   (NOT_A_PIN))
/* Controller counts include unbonded peripherals; route tables only contain valid pins. */
#define STC_VARIANT_UART1_ROUTE_COUNT 4U
#define PIN_SERIAL1_RX P3_0
#define STC_VARIANT_UART1_RX_PIN(route) \
  (((route) == (0U)) ? (P3_0) : \
   ((route) == (1U)) ? (P3_6) : \
   ((route) == (2U)) ? (P1_6) : \
   ((route) == (3U)) ? (P4_3) : \
   (NOT_A_PIN))
#define PIN_SERIAL1_TX P3_1
#define STC_VARIANT_UART1_TX_PIN(route) \
  (((route) == (0U)) ? (P3_1) : \
   ((route) == (1U)) ? (P3_7) : \
   ((route) == (2U)) ? (P1_7) : \
   ((route) == (3U)) ? (P4_4) : \
   (NOT_A_PIN))
#define STC_VARIANT_UART1_ROUTE(left, right) ((((left) == P3_0) && ((right) == P3_1)) ? 0U : (((left) == P3_6) && ((right) == P3_7)) ? 1U : (((left) == P1_6) && ((right) == P1_7)) ? 2U : (((left) == P4_3) && ((right) == P4_4)) ? 3U : 255U)
#define STC_VARIANT_UART2_ROUTE_COUNT 4U
#define PIN_SERIAL2_RX P1_0
#define STC_VARIANT_UART2_RX_PIN(route) \
  (((route) == (0U)) ? (P1_0) : \
   ((route) == (1U)) ? (P4_6) : \
   ((route) == (2U)) ? (P8_4) : \
   ((route) == (3U)) ? (PA_0) : \
   (NOT_A_PIN))
#define PIN_SERIAL2_TX P1_1
#define STC_VARIANT_UART2_TX_PIN(route) \
  (((route) == (0U)) ? (P1_1) : \
   ((route) == (1U)) ? (P4_7) : \
   ((route) == (2U)) ? (P8_5) : \
   ((route) == (3U)) ? (PA_1) : \
   (NOT_A_PIN))
#define STC_VARIANT_UART2_ROUTE(left, right) ((((left) == P1_0) && ((right) == P1_1)) ? 0U : (((left) == P4_6) && ((right) == P4_7)) ? 1U : (((left) == P8_4) && ((right) == P8_5)) ? 2U : (((left) == PA_0) && ((right) == PA_1)) ? 3U : 255U)
#define STC_VARIANT_UART3_ROUTE_COUNT 4U
#define PIN_SERIAL3_RX P0_0
#define STC_VARIANT_UART3_RX_PIN(route) \
  (((route) == (0U)) ? (P0_0) : \
   ((route) == (1U)) ? (P5_0) : \
   ((route) == (2U)) ? (P8_6) : \
   ((route) == (3U)) ? (PB_6) : \
   (NOT_A_PIN))
#define PIN_SERIAL3_TX P0_1
#define STC_VARIANT_UART3_TX_PIN(route) \
  (((route) == (0U)) ? (P0_1) : \
   ((route) == (1U)) ? (P5_1) : \
   ((route) == (2U)) ? (P8_7) : \
   ((route) == (3U)) ? (PB_7) : \
   (NOT_A_PIN))
#define STC_VARIANT_UART3_ROUTE(left, right) ((((left) == P0_0) && ((right) == P0_1)) ? 0U : (((left) == P5_0) && ((right) == P5_1)) ? 1U : (((left) == P8_6) && ((right) == P8_7)) ? 2U : (((left) == PB_6) && ((right) == PB_7)) ? 3U : 255U)
#define STC_VARIANT_UART4_ROUTE_COUNT 3U
#define PIN_SERIAL4_RX P0_2
#define STC_VARIANT_UART4_RX_PIN(route) \
  (((route) == (0U)) ? (P0_2) : \
   ((route) == (1U)) ? (P5_2) : \
   ((route) == (2U)) ? (PA_2) : \
   (NOT_A_PIN))
#define PIN_SERIAL4_TX P0_3
#define STC_VARIANT_UART4_TX_PIN(route) \
  (((route) == (0U)) ? (P0_3) : \
   ((route) == (1U)) ? (P5_3) : \
   ((route) == (2U)) ? (PA_3) : \
   (NOT_A_PIN))
#define STC_VARIANT_UART4_ROUTE(left, right) ((((left) == P0_2) && ((right) == P0_3)) ? 0U : (((left) == P5_2) && ((right) == P5_3)) ? 1U : (((left) == PA_2) && ((right) == PA_3)) ? 2U : 255U)
#define STC_VARIANT_UART5_ROUTE_COUNT 4U
#define PIN_SERIAL5_RX P0_4
#define STC_VARIANT_UART5_RX_PIN(route) \
  (((route) == (0U)) ? (P0_4) : \
   ((route) == (1U)) ? (P4_0) : \
   ((route) == (2U)) ? (P1_4) : \
   ((route) == (3U)) ? (P2_0) : \
   (NOT_A_PIN))
#define PIN_SERIAL5_TX P0_5
#define STC_VARIANT_UART5_TX_PIN(route) \
  (((route) == (0U)) ? (P0_5) : \
   ((route) == (1U)) ? (P4_1) : \
   ((route) == (2U)) ? (P1_5) : \
   ((route) == (3U)) ? (P2_1) : \
   (NOT_A_PIN))
#define STC_VARIANT_UART5_ROUTE(left, right) ((((left) == P0_4) && ((right) == P0_5)) ? 0U : (((left) == P4_0) && ((right) == P4_1)) ? 1U : (((left) == P1_4) && ((right) == P1_5)) ? 2U : (((left) == P2_0) && ((right) == P2_1)) ? 3U : 255U)
#define STC_VARIANT_UART6_ROUTE_COUNT 4U
#define PIN_SERIAL6_RX P0_6
#define STC_VARIANT_UART6_RX_PIN(route) \
  (((route) == (0U)) ? (P0_6) : \
   ((route) == (1U)) ? (P6_2) : \
   ((route) == (2U)) ? (P3_2) : \
   ((route) == (3U)) ? (P2_6) : \
   (NOT_A_PIN))
#define PIN_SERIAL6_TX P0_7
#define STC_VARIANT_UART6_TX_PIN(route) \
  (((route) == (0U)) ? (P0_7) : \
   ((route) == (1U)) ? (P6_3) : \
   ((route) == (2U)) ? (P3_3) : \
   ((route) == (3U)) ? (P2_7) : \
   (NOT_A_PIN))
#define STC_VARIANT_UART6_ROUTE(left, right) ((((left) == P0_6) && ((right) == P0_7)) ? 0U : (((left) == P6_2) && ((right) == P6_3)) ? 1U : (((left) == P3_2) && ((right) == P3_3)) ? 2U : (((left) == P2_6) && ((right) == P2_7)) ? 3U : 255U)
#define STC_VARIANT_UART7_ROUTE_COUNT 3U
#define PIN_SERIAL7_RX P5_0
#define STC_VARIANT_UART7_RX_PIN(route) \
  (((route) == (0U)) ? (P5_0) : \
   ((route) == (1U)) ? (PA_4) : \
   ((route) == (2U)) ? (P9_0) : \
   (NOT_A_PIN))
#define PIN_SERIAL7_TX P5_1
#define STC_VARIANT_UART7_TX_PIN(route) \
  (((route) == (0U)) ? (P5_1) : \
   ((route) == (1U)) ? (PA_5) : \
   ((route) == (2U)) ? (P9_1) : \
   (NOT_A_PIN))
#define STC_VARIANT_UART7_ROUTE(left, right) ((((left) == P5_0) && ((right) == P5_1)) ? 0U : (((left) == PA_4) && ((right) == PA_5)) ? 1U : (((left) == P9_0) && ((right) == P9_1)) ? 2U : 255U)
#define STC_VARIANT_UART8_ROUTE_COUNT 4U
#define PIN_SERIAL8_RX P5_2
#define STC_VARIANT_UART8_RX_PIN(route) \
  (((route) == (0U)) ? (P5_2) : \
   ((route) == (1U)) ? (PA_6) : \
   ((route) == (2U)) ? (P9_2) : \
   ((route) == (3U)) ? (P6_0) : \
   (NOT_A_PIN))
#define PIN_SERIAL8_TX P5_3
#define STC_VARIANT_UART8_TX_PIN(route) \
  (((route) == (0U)) ? (P5_3) : \
   ((route) == (1U)) ? (PA_7) : \
   ((route) == (2U)) ? (P9_3) : \
   ((route) == (3U)) ? (P6_1) : \
   (NOT_A_PIN))
#define STC_VARIANT_UART8_ROUTE(left, right) ((((left) == P5_2) && ((right) == P5_3)) ? 0U : (((left) == PA_6) && ((right) == PA_7)) ? 1U : (((left) == P9_2) && ((right) == P9_3)) ? 2U : (((left) == P6_0) && ((right) == P6_1)) ? 3U : 255U)
#define STC_VARIANT_I2C1_ROUTE_COUNT 4U
#define PIN_I2C1_SDA P3_3
#define STC_VARIANT_I2C1_SDA_PIN(route) \
  (((route) == (0U)) ? (P1_4) : \
   ((route) == (1U)) ? (P2_4) : \
   ((route) == (2U)) ? (P7_6) : \
   ((route) == (3U)) ? (P3_3) : \
   (NOT_A_PIN))
#define PIN_I2C1_SCL P3_2
#define STC_VARIANT_I2C1_SCL_PIN(route) \
  (((route) == (0U)) ? (P1_5) : \
   ((route) == (1U)) ? (P2_5) : \
   ((route) == (2U)) ? (P7_7) : \
   ((route) == (3U)) ? (P3_2) : \
   (NOT_A_PIN))
#define STC_VARIANT_I2C1_ROUTE(left, right) ((((left) == P1_4) && ((right) == P1_5)) ? 0U : (((left) == P2_4) && ((right) == P2_5)) ? 1U : (((left) == P7_6) && ((right) == P7_7)) ? 2U : (((left) == P3_3) && ((right) == P3_2)) ? 3U : 255U)
#define STC_VARIANT_I2C2_ROUTE_COUNT 4U
#define PIN_I2C2_SDA P2_6
#define STC_VARIANT_I2C2_SDA_PIN(route) \
  (((route) == (0U)) ? (P2_6) : \
   ((route) == (1U)) ? (P3_6) : \
   ((route) == (2U)) ? (P1_6) : \
   ((route) == (3U)) ? (P6_0) : \
   (NOT_A_PIN))
#define PIN_I2C2_SCL P2_7
#define STC_VARIANT_I2C2_SCL_PIN(route) \
  (((route) == (0U)) ? (P2_7) : \
   ((route) == (1U)) ? (P3_7) : \
   ((route) == (2U)) ? (P1_7) : \
   ((route) == (3U)) ? (P6_1) : \
   (NOT_A_PIN))
#define STC_VARIANT_I2C2_ROUTE(left, right) ((((left) == P2_6) && ((right) == P2_7)) ? 0U : (((left) == P3_6) && ((right) == P3_7)) ? 1U : (((left) == P1_6) && ((right) == P1_7)) ? 2U : (((left) == P6_0) && ((right) == P6_1)) ? 3U : 255U)
#define PIN_SERIAL_RX PIN_SERIAL1_RX
#define PIN_SERIAL_TX PIN_SERIAL1_TX
#define PIN_WIRE1_SDA PIN_I2C2_SDA
#define PIN_WIRE1_SCL PIN_I2C2_SCL
#define STC_VARIANT_SPI1_ROUTE_COUNT 4U
#define PIN_SPI1_MOSI P1_3
#define STC_VARIANT_SPI1_MOSI_PIN(route) \
  (((route) == (0U)) ? (P1_3) : \
   ((route) == (1U)) ? (P2_3) : \
   ((route) == (2U)) ? (P4_0) : \
   ((route) == (3U)) ? (P3_4) : \
   (NOT_A_PIN))
#define PIN_SPI1_MISO P1_4
#define STC_VARIANT_SPI1_MISO_PIN(route) \
  (((route) == (0U)) ? (P1_4) : \
   ((route) == (1U)) ? (P2_4) : \
   ((route) == (2U)) ? (P4_1) : \
   ((route) == (3U)) ? (P3_3) : \
   (NOT_A_PIN))
#define PIN_SPI1_SCK P1_5
#define STC_VARIANT_SPI1_SCK_PIN(route) \
  (((route) == (0U)) ? (P1_5) : \
   ((route) == (1U)) ? (P2_5) : \
   ((route) == (2U)) ? (P4_3) : \
   ((route) == (3U)) ? (P3_2) : \
   (NOT_A_PIN))
#define PIN_SPI1_SS P5_4
#define STC_VARIANT_SPI1_ROUTE(mosi, miso, sck) ((((mosi) == P1_3) && ((miso) == P1_4) && ((sck) == P1_5)) ? 0U : (((mosi) == P2_3) && ((miso) == P2_4) && ((sck) == P2_5)) ? 1U : (((mosi) == P4_0) && ((miso) == P4_1) && ((sck) == P4_3)) ? 2U : (((mosi) == P3_4) && ((miso) == P3_3) && ((sck) == P3_2)) ? 3U : 255U)
#define STC_VARIANT_SPI2_ROUTE_COUNT 4U
#define PIN_SPI2_MOSI P6_5
#define STC_VARIANT_SPI2_MOSI_PIN(route) \
  (((route) == (0U)) ? (P6_5) : \
   ((route) == (1U)) ? (P0_3) : \
   ((route) == (2U)) ? (PB_2) : \
   ((route) == (3U)) ? (P8_1) : \
   (NOT_A_PIN))
#define PIN_SPI2_MISO P6_6
#define STC_VARIANT_SPI2_MISO_PIN(route) \
  (((route) == (0U)) ? (P6_6) : \
   ((route) == (1U)) ? (P0_4) : \
   ((route) == (2U)) ? (PB_3) : \
   ((route) == (3U)) ? (P8_2) : \
   (NOT_A_PIN))
#define PIN_SPI2_SCK P6_7
#define STC_VARIANT_SPI2_SCK_PIN(route) \
  (((route) == (0U)) ? (P6_7) : \
   ((route) == (1U)) ? (P0_5) : \
   ((route) == (2U)) ? (PB_4) : \
   ((route) == (3U)) ? (P8_3) : \
   (NOT_A_PIN))
#define PIN_SPI2_SS P6_4
#define STC_VARIANT_SPI2_ROUTE(mosi, miso, sck) ((((mosi) == P6_5) && ((miso) == P6_6) && ((sck) == P6_7)) ? 0U : (((mosi) == P0_3) && ((miso) == P0_4) && ((sck) == P0_5)) ? 1U : (((mosi) == PB_2) && ((miso) == PB_3) && ((sck) == PB_4)) ? 2U : (((mosi) == P8_1) && ((miso) == P8_2) && ((sck) == P8_3)) ? 3U : 255U)
#define STC_VARIANT_SPI3_ROUTE_COUNT 4U
#define PIN_SPI3_MOSI P2_3
#define STC_VARIANT_SPI3_MOSI_PIN(route) \
  (((route) == (0U)) ? (P2_3) : \
   ((route) == (1U)) ? (P7_1) : \
   ((route) == (2U)) ? (P8_5) : \
   ((route) == (3U)) ? (P9_1) : \
   (NOT_A_PIN))
#define PIN_SPI3_MISO P2_4
#define STC_VARIANT_SPI3_MISO_PIN(route) \
  (((route) == (0U)) ? (P2_4) : \
   ((route) == (1U)) ? (P7_2) : \
   ((route) == (2U)) ? (P8_6) : \
   ((route) == (3U)) ? (P9_2) : \
   (NOT_A_PIN))
#define PIN_SPI3_SCK P2_5
#define STC_VARIANT_SPI3_SCK_PIN(route) \
  (((route) == (0U)) ? (P2_5) : \
   ((route) == (1U)) ? (P7_3) : \
   ((route) == (2U)) ? (P8_7) : \
   ((route) == (3U)) ? (P9_3) : \
   (NOT_A_PIN))
#define PIN_SPI3_SS P2_2
#define STC_VARIANT_SPI3_ROUTE(mosi, miso, sck) ((((mosi) == P2_3) && ((miso) == P2_4) && ((sck) == P2_5)) ? 0U : (((mosi) == P7_1) && ((miso) == P7_2) && ((sck) == P7_3)) ? 1U : (((mosi) == P8_5) && ((miso) == P8_6) && ((sck) == P8_7)) ? 2U : (((mosi) == P9_1) && ((miso) == P9_2) && ((sck) == P9_3)) ? 3U : 255U)
#define STC_VARIANT_HAS_ADC 1
#define STC_VARIANT_ADC_LAYOUT 4U
#define STC_VARIANT_ADC_NATIVE_BITS 12U
#define STC_VARIANT_ADC_BITS STC_VARIANT_ADC_NATIVE_BITS
#define STC_VARIANT_ADC_CHANNEL_COUNT 11U
#define NUM_ANALOG_INPUTS 11
#define A0 P1_0
#define A1 P1_1
#define A2 P5_4
#define A3 P1_3
#define A4 P1_4
#define A5 P1_5
#define A6 P1_6
#define A7 P1_7
#define A8 P0_0
#define A9 P0_1
#define A10 P0_2
#define STC_VARIANT_FIRST_ANALOG_PIN A0
#define STC_VARIANT_LAST_ANALOG_PIN A10
#define analogInputToDigitalPin(index) \
  (((index) == (0U)) ? (P1_0) : \
   ((index) == (1U)) ? (P1_1) : \
   ((index) == (2U)) ? (P5_4) : \
   ((index) == (3U)) ? (P1_3) : \
   ((index) == (4U)) ? (P1_4) : \
   ((index) == (5U)) ? (P1_5) : \
   ((index) == (6U)) ? (P1_6) : \
   ((index) == (7U)) ? (P1_7) : \
   ((index) == (8U)) ? (P0_0) : \
   ((index) == (9U)) ? (P0_1) : \
   ((index) == (10U)) ? (P0_2) : \
   (NOT_A_PIN))
#define digitalPinToAnalogInput(pin) \
  (((pin) == (P1_0)) ? (0U) : \
   ((pin) == (P1_1)) ? (1U) : \
   ((pin) == (P5_4)) ? (2U) : \
   ((pin) == (P1_3)) ? (3U) : \
   ((pin) == (P1_4)) ? (4U) : \
   ((pin) == (P1_5)) ? (5U) : \
   ((pin) == (P1_6)) ? (6U) : \
   ((pin) == (P1_7)) ? (7U) : \
   ((pin) == (P0_0)) ? (8U) : \
   ((pin) == (P0_1)) ? (9U) : \
   ((pin) == (P0_2)) ? (10U) : \
   (NOT_AN_ANALOG_INPUT))
#define STC_VARIANT_ADC_PIN_TO_CHANNEL(pin) \
  (((pin) == (P1_0)) ? (0U) : \
   ((pin) == (P1_1)) ? (1U) : \
   ((pin) == (P5_4)) ? (2U) : \
   ((pin) == (P1_3)) ? (3U) : \
   ((pin) == (P1_4)) ? (4U) : \
   ((pin) == (P1_5)) ? (5U) : \
   ((pin) == (P1_6)) ? (6U) : \
   ((pin) == (P1_7)) ? (7U) : \
   ((pin) == (P0_0)) ? (8U) : \
   ((pin) == (P0_1)) ? (9U) : \
   ((pin) == (P0_2)) ? (10U) : \
   (NOT_AN_ADC_CHANNEL))

#include "../_common/pins_arduino_common.h"

#endif
