// Generated by tools/variants/generate.mjs; edit devices.json / peripherals.json instead.
#ifndef ARDUINO_VARIANT_AI8051U_34K16_H
#define ARDUINO_VARIANT_AI8051U_34K16_H

#define STC_VARIANT_MODEL "AI8051U-34K16"
#define STC_VARIANT_FAMILY "AI8051U"
#define STC_FLASH_BYTES 16384UL
#define STC_MAXIMUM_CODE_BYTES 16384UL
#define STC_IDATA_BYTES 256U
#define STC_XDATA_BYTES 32768UL
#define STC_EDATA_BYTES 2048UL
#define STC_NUM_LOGICAL_DIGITAL_PINS 46U
#define STC_NUM_BONDED_DIGITAL_PINS 45U
#define STC_VARIANT_PIN_ALIAS_GROUP_COUNT 1U
#define STC_PINOUT_IS_PACKAGE_DEPENDENT 1
#define STC_VARIANT_HAS_SEPARATE_PULLUP 0
#define STC_VARIANT_HAS_UART1 1
#define STC_VARIANT_UART_COUNT 4U
#define STC_VARIANT_I2C_COUNT 1U
#define STC_VARIANT_SPI_COUNT 1U
#define STC_VARIANT_SERIAL_BUFFERED_RX 1
#define PIN_VALID_MASK_P0 0xFFU
#define PIN_VALID_MASK_P1 0xFFU
#define PIN_VALID_MASK_P2 0xFFU
#define PIN_VALID_MASK_P3 0xFFU
#define PIN_VALID_MASK_P4 0xFFU
#define PIN_VALID_MASK_P5 0xCFU
#define PIN_VALID_MASK_P6 0x00U
#define PIN_VALID_MASK_P7 0x00U
#define PIN_VALID_MASK_P8 0x00U
#define PIN_VALID_MASK_P9 0x00U
#define PIN_VALID_MASK_PA 0x00U
#define PIN_VALID_MASK_PB 0x00U
#define STC_VARIANT_PINS_SHARE_PHYSICAL_PAD(left, right) \
  (((((left) == (P4_4)) && ((right) == (P4_5))) || (((left) == (P4_5)) && ((right) == (P4_4)))))
#define STC_VARIANT_PHYSICAL_ALIAS(pin) \
  (((pin) == (P4_4)) ? (P4_5) : \
   ((pin) == (P4_5)) ? (P4_4) : \
   (NOT_A_PIN))
/* Controller counts include unbonded peripherals; route tables only contain valid pins. */
#define STC_VARIANT_UART1_ROUTE_COUNT 4U
#define PIN_SERIAL1_RX P3_0
#define STC_VARIANT_UART1_RX_PIN(route) \
  (((route) == (0U)) ? (P3_0) : \
   ((route) == (1U)) ? (P3_6) : \
   ((route) == (2U)) ? (P1_6) : \
   ((route) == (3U)) ? (P4_3) : \
   (NOT_A_PIN))
#define PIN_SERIAL1_TX P3_1
#define STC_VARIANT_UART1_TX_PIN(route) \
  (((route) == (0U)) ? (P3_1) : \
   ((route) == (1U)) ? (P3_7) : \
   ((route) == (2U)) ? (P1_7) : \
   ((route) == (3U)) ? (P4_4) : \
   (NOT_A_PIN))
#define STC_VARIANT_UART1_ROUTE(left, right) ((((left) == P3_0) && ((right) == P3_1)) ? 0U : (((left) == P3_6) && ((right) == P3_7)) ? 1U : (((left) == P1_6) && ((right) == P1_7)) ? 2U : (((left) == P4_3) && ((right) == P4_4)) ? 3U : 255U)
#define STC_VARIANT_UART2_ROUTE_COUNT 2U
#define PIN_SERIAL2_RX P1_2
#define STC_VARIANT_UART2_RX_PIN(route) \
  (((route) == (0U)) ? (P1_2) : \
   ((route) == (1U)) ? (P4_2) : \
   (NOT_A_PIN))
#define PIN_SERIAL2_TX P1_3
#define STC_VARIANT_UART2_TX_PIN(route) \
  (((route) == (0U)) ? (P1_3) : \
   ((route) == (1U)) ? (P4_3) : \
   (NOT_A_PIN))
#define STC_VARIANT_UART2_ROUTE(left, right) ((((left) == P1_2) && ((right) == P1_3)) ? 0U : (((left) == P4_2) && ((right) == P4_3)) ? 1U : 255U)
#define STC_VARIANT_UART3_ROUTE_COUNT 2U
#define PIN_SERIAL3_RX P0_0
#define STC_VARIANT_UART3_RX_PIN(route) \
  (((route) == (0U)) ? (P0_0) : \
   ((route) == (1U)) ? (P5_0) : \
   (NOT_A_PIN))
#define PIN_SERIAL3_TX P0_1
#define STC_VARIANT_UART3_TX_PIN(route) \
  (((route) == (0U)) ? (P0_1) : \
   ((route) == (1U)) ? (P5_1) : \
   (NOT_A_PIN))
#define STC_VARIANT_UART3_ROUTE(left, right) ((((left) == P0_0) && ((right) == P0_1)) ? 0U : (((left) == P5_0) && ((right) == P5_1)) ? 1U : 255U)
#define STC_VARIANT_UART4_ROUTE_COUNT 2U
#define PIN_SERIAL4_RX P0_2
#define STC_VARIANT_UART4_RX_PIN(route) \
  (((route) == (0U)) ? (P0_2) : \
   ((route) == (1U)) ? (P5_2) : \
   (NOT_A_PIN))
#define PIN_SERIAL4_TX P0_3
#define STC_VARIANT_UART4_TX_PIN(route) \
  (((route) == (0U)) ? (P0_3) : \
   ((route) == (1U)) ? (P5_3) : \
   (NOT_A_PIN))
#define STC_VARIANT_UART4_ROUTE(left, right) ((((left) == P0_2) && ((right) == P0_3)) ? 0U : (((left) == P5_2) && ((right) == P5_3)) ? 1U : 255U)
#define STC_VARIANT_I2C1_ROUTE_COUNT 3U
#define PIN_I2C1_SDA P3_3
#define STC_VARIANT_I2C1_SDA_PIN(route) \
  (((route) == (0U)) ? (P2_3) : \
   ((route) == (1U)) ? (P1_4) : \
   ((route) == (3U)) ? (P3_3) : \
   (NOT_A_PIN))
#define PIN_I2C1_SCL P3_2
#define STC_VARIANT_I2C1_SCL_PIN(route) \
  (((route) == (0U)) ? (P2_4) : \
   ((route) == (1U)) ? (P1_5) : \
   ((route) == (3U)) ? (P3_2) : \
   (NOT_A_PIN))
#define STC_VARIANT_I2C1_ROUTE(left, right) ((((left) == P2_3) && ((right) == P2_4)) ? 0U : (((left) == P1_4) && ((right) == P1_5)) ? 1U : (((left) == P3_3) && ((right) == P3_2)) ? 3U : 255U)
#define PIN_SERIAL_RX PIN_SERIAL1_RX
#define PIN_SERIAL_TX PIN_SERIAL1_TX
#define STC_VARIANT_SPI1_ROUTE_COUNT 4U
#define PIN_SPI1_MOSI P1_5
#define STC_VARIANT_SPI1_MOSI_PIN(route) \
  (((route) == (0U)) ? (P1_5) : \
   ((route) == (1U)) ? (P2_5) : \
   ((route) == (2U)) ? (P4_1) : \
   ((route) == (3U)) ? (P3_4) : \
   (NOT_A_PIN))
#define PIN_SPI1_MISO P1_6
#define STC_VARIANT_SPI1_MISO_PIN(route) \
  (((route) == (0U)) ? (P1_6) : \
   ((route) == (1U)) ? (P2_6) : \
   ((route) == (2U)) ? (P4_2) : \
   ((route) == (3U)) ? (P3_3) : \
   (NOT_A_PIN))
#define PIN_SPI1_SCK P1_7
#define STC_VARIANT_SPI1_SCK_PIN(route) \
  (((route) == (0U)) ? (P1_7) : \
   ((route) == (1U)) ? (P2_7) : \
   ((route) == (2U)) ? (P4_3) : \
   ((route) == (3U)) ? (P3_2) : \
   (NOT_A_PIN))
#define PIN_SPI1_SS P1_4
#define STC_VARIANT_SPI1_ROUTE(mosi, miso, sck) ((((mosi) == P1_5) && ((miso) == P1_6) && ((sck) == P1_7)) ? 0U : (((mosi) == P2_5) && ((miso) == P2_6) && ((sck) == P2_7)) ? 1U : (((mosi) == P4_1) && ((miso) == P4_2) && ((sck) == P4_3)) ? 2U : (((mosi) == P3_4) && ((miso) == P3_3) && ((sck) == P3_2)) ? 3U : 255U)
#define STC_VARIANT_HAS_ADC 1
#define STC_VARIANT_ADC_LAYOUT 4U
#define STC_VARIANT_ADC_NATIVE_BITS 12U
#define STC_VARIANT_ADC_BITS STC_VARIANT_ADC_NATIVE_BITS
#define STC_VARIANT_ADC_CHANNEL_COUNT 15U
#define NUM_ANALOG_INPUTS 15
#define A0 P1_0
#define A1 P1_1
#define A2 P1_2
#define A3 P1_3
#define A4 P1_4
#define A5 P1_5
#define A6 P1_6
#define A7 P1_7
#define A8 P0_0
#define A9 P0_1
#define A10 P0_2
#define A11 P0_3
#define A12 P0_4
#define A13 P0_5
#define A14 P0_6
#define STC_VARIANT_FIRST_ANALOG_PIN A0
#define STC_VARIANT_LAST_ANALOG_PIN A14
#define analogInputToDigitalPin(index) \
  (((index) == (0U)) ? (P1_0) : \
   ((index) == (1U)) ? (P1_1) : \
   ((index) == (2U)) ? (P1_2) : \
   ((index) == (3U)) ? (P1_3) : \
   ((index) == (4U)) ? (P1_4) : \
   ((index) == (5U)) ? (P1_5) : \
   ((index) == (6U)) ? (P1_6) : \
   ((index) == (7U)) ? (P1_7) : \
   ((index) == (8U)) ? (P0_0) : \
   ((index) == (9U)) ? (P0_1) : \
   ((index) == (10U)) ? (P0_2) : \
   ((index) == (11U)) ? (P0_3) : \
   ((index) == (12U)) ? (P0_4) : \
   ((index) == (13U)) ? (P0_5) : \
   ((index) == (14U)) ? (P0_6) : \
   (NOT_A_PIN))
#define digitalPinToAnalogInput(pin) \
  (((pin) == (P1_0)) ? (0U) : \
   ((pin) == (P1_1)) ? (1U) : \
   ((pin) == (P1_2)) ? (2U) : \
   ((pin) == (P1_3)) ? (3U) : \
   ((pin) == (P1_4)) ? (4U) : \
   ((pin) == (P1_5)) ? (5U) : \
   ((pin) == (P1_6)) ? (6U) : \
   ((pin) == (P1_7)) ? (7U) : \
   ((pin) == (P0_0)) ? (8U) : \
   ((pin) == (P0_1)) ? (9U) : \
   ((pin) == (P0_2)) ? (10U) : \
   ((pin) == (P0_3)) ? (11U) : \
   ((pin) == (P0_4)) ? (12U) : \
   ((pin) == (P0_5)) ? (13U) : \
   ((pin) == (P0_6)) ? (14U) : \
   (NOT_AN_ANALOG_INPUT))
#define STC_VARIANT_ADC_PIN_TO_CHANNEL(pin) \
  (((pin) == (P1_0)) ? (0U) : \
   ((pin) == (P1_1)) ? (1U) : \
   ((pin) == (P1_2)) ? (2U) : \
   ((pin) == (P1_3)) ? (3U) : \
   ((pin) == (P1_4)) ? (4U) : \
   ((pin) == (P1_5)) ? (5U) : \
   ((pin) == (P1_6)) ? (6U) : \
   ((pin) == (P1_7)) ? (7U) : \
   ((pin) == (P0_0)) ? (8U) : \
   ((pin) == (P0_1)) ? (9U) : \
   ((pin) == (P0_2)) ? (10U) : \
   ((pin) == (P0_3)) ? (11U) : \
   ((pin) == (P0_4)) ? (12U) : \
   ((pin) == (P0_5)) ? (13U) : \
   ((pin) == (P0_6)) ? (14U) : \
   (NOT_AN_ADC_CHANNEL))

#include "../_common/pins_arduino_common.h"

#endif
